services: 

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 9000:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s  
      timeout: 5s
      retries: 50
    volumes:
      - ./src/:/app/src

  app:

    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 8000:8000