version: "3.9"

services:
  app:
    restart: unless-stopped
    build: .
    container_name: ToDO-API
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env

volumes:
  app:

